### ISSUE TITLE
wider_annotation key error

### ISSUE THREAD

**Issue by mengzhibin** [SpikeKing/keras-yolo3-detection#8]
hi, when i convert the training file, i met some error as below:
Traceback (most recent call last):
  File "wider_annotation.py", line 137, in <module>
    generate_train_file(train_bbx_file, train_data_folder, out_file)
  File "wider_annotation.py", line 44, in generate_train_file
    img_path = name_dict[name]
KeyError: '2_Demonstration_Political_Rally_2_620.jpg'

Could you help tell what happened? thank you very much.
@SpikeKing

**Comment by gittigxuy** [comment]
I guess you have wrong road,in my environment,I generate WIDER_train.txt file,or could you please send your error screenshot?I think you could easyly debug by yourself
